const professions = [
    { name: "Oncologist", insurance: "Healthcare" },
    { name: "Software Developer", insurance: "Tech" },
    { name: "Financial Analyst", insurance: "FinTech" },
    { name: "IT Security Specialist", insurance: "Tech" },
    { name: "Data Analyst", insurance: "Tech" },
    { name: "Network Administrator", insurance: "Tech" },
    { name: "System Administrator", insurance: "Tech" },
    { name: "Web Developer", insurance: "Tech" },
    { name: "Cybersecurity Consultant", insurance: "Tech" },
    { name: "Information Security Officer", insurance: "Tech" },
    { name: "Ethical Hacker", insurance: "Tech" },
    { name: "Data Privacy Officer", insurance: "Tech" },
    { name: "IT Auditor", insurance: "Tech" },
    { name: "Banker", insurance: "Financial Institutions" },
    { name: "Investment Advisor", insurance: "Financial Institutions" },
    { name: "Loan Officer", insurance: "Financial Institutions" },
    { name: "Credit Analyst", insurance: "Financial Institutions" },
    { name: "Financial Planner", insurance: "Financial Institutions" },
    { name: "Mortgage Broker", insurance: "Financial Institutions" },
    { name: "Risk Analyst", insurance: "Financial Institutions" },
    { name: "Compliance Officer", insurance: "Financial Institutions" },
    { name: "Asset Manager", insurance: "Financial Institutions" },
    { name: "Wealth Manager", insurance: "Financial Institutions" },
    { name: "Blockchain Developer", insurance: "FinTech" },
    { name: "FinTech Product Manager", insurance: "FinTech" },
    { name: "Mobile Payment Developer", insurance: "FinTech" },
    { name: "Robo-Advisor Developer", insurance: "FinTech" },
    { name: "Cryptocurrency Trader", insurance: "FinTech" },
    { name: "InsurTech Specialist", insurance: "FinTech" },
    { name: "Payment Processor", insurance: "FinTech" },
    { name: "FinTech Compliance Specialist", insurance: "FinTech" },
    { name: "Digital Currency Analyst", insurance: "FinTech" },
    { name: "Biotech Researcher", insurance: "Life Sciences" },
    { name: "Pharmaceutical Scientist", insurance: "Life Sciences" },
    { name: "Clinical Trial Manager", insurance: "Life Sciences" },
    { name: "Biomedical Engineer", insurance: "Life Sciences" },
    { name: "Medical Device Developer", insurance: "Life Sciences" },
    { name: "Genetic Engineer", insurance: "Life Sciences" },
    { name: "Bioinformatics Specialist", insurance: "Life Sciences" },
    { name: "Toxicologist", insurance: "Life Sciences" },
    { name: "Clinical Research Associate", insurance: "Life Sciences" },
    { name: "Regulatory Affairs Specialist", insurance: "Life Sciences" },
    { name: "CEO", insurance: "Management Liability" },
    { name: "CFO", insurance: "Management Liability" },
    { name: "Board Member", insurance: "Management Liability" },
    { name: "Director", insurance: "Management Liability" },
    { name: "Corporate Secretary", insurance: "Management Liability" },
    { name: "COO", insurance: "Management Liability" },
    { name: "President", insurance: "Management Liability" },
    { name: "Vice President", insurance: "Management Liability" },
    { name: "Chief Legal Officer", insurance: "Management Liability" },
    { name: "Chief Compliance Officer", insurance: "Management Liability" },
    { name: "Journalist", insurance: "Media" },
    { name: "TV Producer", insurance: "Media" },
    { name: "Radio Host", insurance: "Media" },
    { name: "Public Relations Specialist", insurance: "Media" },
    { name: "Digital Content Creator", insurance: "Media" },
    { name: "Social Media Manager", insurance: "Media" },
    { name: "Broadcast Engineer", insurance: "Media" },
    { name: "News Anchor", insurance: "Media" },
    { name: "Film Director", insurance: "Media" },
    { name: "Video Editor", insurance: "Media" },
    { name: "Product Safety Engineer", insurance: "Product Recall" },
    { name: "Quality Control Specialist", insurance: "Product Recall" },
    { name: "Recall Coordinator", insurance: "Product Recall" },
    { name: "Compliance Officer", insurance: "Product Recall" },
    { name: "Manufacturing Engineer", insurance: "Product Recall" },
    { name: "Consumer Safety Officer", insurance: "Product Recall" },
    { name: "Quality Assurance Manager", insurance: "Product Recall" },
    { name: "Production Supervisor", insurance: "Product Recall" },
    { name: "Product Development Scientist", insurance: "Product Recall" },
    { name: "Food Safety Inspector", insurance: "Product Recall" },
    { name: "Lawyer", insurance: "Professions" },
    { name: "Accountant", insurance: "Professions" },
    { name: "Consultant", insurance: "Professions" },
    { name: "Real Estate Agent", insurance: "Professions" },
    { name: "Graphic Designer", insurance: "Professions" },
    { name: "Marketing Consultant", insurance: "Professions" },
    { name: "Business Analyst", insurance: "Professions" },
    { name: "Management Consultant", insurance: "Professions" },
    { name: "Architect", insurance: "Professions" },
    { name: "Engineer", insurance: "Professions" },
    { name: "Construction Manager", insurance: "Property & Casualty" },
    { name: "Property Manager", insurance: "Property & Casualty" },
    { name: "Claims Adjuster", insurance: "Property & Casualty" },
    { name: "Underwriter", insurance: "Property & Casualty" },
    { name: "Risk Manager", insurance: "Property & Casualty" },
    { name: "Building Inspector", insurance: "Property & Casualty" },
    { name: "Insurance Broker", insurance: "Property & Casualty" },
    { name: "Loss Control Specialist", insurance: "Property & Casualty" },
    { name: "Fleet Manager", insurance: "Property & Casualty" },
    { name: "Safety Coordinator", insurance: "Property & Casualty" },
    { name: "Software Engineer", insurance: "Tech" },
    { name: "Data Scientist", insurance: "Tech" },
    { name: "AI Developer", insurance: "Tech" },
    { name: "Hardware Engineer", insurance: "Tech" },
    { name: "Tech Support Specialist", insurance: "Tech" },
    { name: "Systems Analyst", insurance: "Tech" },
    { name: "Network Architect", insurance: "Tech" },
    { name: "Database Administrator", insurance: "Tech" },
    { name: "Cloud Solutions Architect", insurance: "Tech" },
    { name: "DevOps Engineer", insurance: "Tech" },
    { name: "Healthcare Administrator", insurance: "Healthcare" },
    { name: "Nurse", insurance: "Healthcare" },
    { name: "Doctor", insurance: "Healthcare" },
    { name: "Medical Researcher", insurance: "Healthcare" },
    { name: "Public Health Specialist", insurance: "Healthcare" },
    { name: "Pharmacist", insurance: "Healthcare" },
    { name: "Surgeon", insurance: "Healthcare" },
    { name: "Dentist", insurance: "Healthcare" },
    { name: "Physical Therapist", insurance: "Healthcare" },
    { name: "Occupational Therapist", insurance: "Healthcare" },
    { name: "Veterinarian", insurance: "Healthcare" },
    { name: "Speech-Language Pathologist", insurance: "Healthcare" },
    { name: "Psychiatrist", insurance: "Healthcare" },
    { name: "Psychologist", insurance: "Healthcare" },
    { name: "Radiologist", insurance: "Healthcare" },
    { name: "Anesthesiologist", insurance: "Healthcare" },
    { name: "Emergency Medical Technician", insurance: "Healthcare" },
    { name: "Paramedic", insurance: "Healthcare" },
    { name: "Respiratory Therapist", insurance: "Healthcare" },
    { name: "Optometrist", insurance: "Healthcare" },
    { name: "Audiologist", insurance: "Healthcare" },
    { name: "Dietitian", insurance: "Healthcare" },
    { name: "Social Worker", insurance: "Healthcare" },
    { name: "Chiropractor", insurance: "Healthcare" },
    { name: "Midwife", insurance: "Healthcare" },
    { name: "Medical Laboratory Scientist", insurance: "Healthcare" },
    { name: "Genetic Counselor", insurance: "Healthcare" },
    { name: "Clinical Pharmacist", insurance: "Healthcare" },
    { name: "Biostatistician", insurance: "Healthcare" },
    { name: "Medical Illustrator", insurance: "Healthcare" },
    { name: "Epidemiologist", insurance: "Healthcare" },
    { name: "Health Information Technician", insurance: "Healthcare" },
    { name: "Clinical Psychologist", insurance: "Healthcare" },
    { name: "Orthopedic Surgeon", insurance: "Healthcare" },
    { name: "Pediatrician", insurance: "Healthcare" },
    { name: "Oncologist", insurance: "Healthcare" },
    { name: "Cardiac Surgeon", insurance: "Healthcare" },
    { name: "Neonatologist", insurance: "Healthcare" },
    { name: "Occupational Health Specialist", insurance: "Healthcare" },
    { name: "Hospice Care Specialist", insurance: "Healthcare" },
    { name: "Geriatrician", insurance: "Healthcare" }
];

const keywordsData = {
    "Property & Casualty": {
        keywords: [
            "Building",
            "Combined liability",
            "Commercial combined",
            "Commercial Property",
            "Construction",
            "Environmental Impairment Liability (EIL)",
            "Location",
            "Office and retail premises",
            "Property",
            "Property managers / owners (commercial and residential)",
            "Residential Dwelling",
            "Specialist contractors (electrical, flooring, shop fitters)",
            "Tourist attractions",
            "Amusement arcades",
            "Construction projects",
            "General contractor",
            "Nightclubs and bars",
            "Standalone property cover"
        ],
        avoid: [
            "Animal Products",
            "Bio",
            "Biotics",
            "Blood bank",
            "Cannabis",
            "CBD",
            "Clinical Trials",
            "Drugs",
            "Hemp",
            "Laboratories",
            "Medical Devices (MD)",
            "Natural Health Products",
            "Nutra",
            "Nutraceuticals",
            "Pain relief",
            "Patients",
            "Pharmaceuticals",
            "Research & Development (R&D)",
            "Research Trials",
            "Stem cell bank",
            "Supplements",
            "Therapeutic devices",
            "Vitamins"
        ]
    },
    "Product Recall": {
        keywords: [
            "Ancillary product recall costs",
            "Contamination",
            "Product recall"
        ]
    },
    "Financial Institutions": {
        keywords: [
            "Asset Management",
            "Bank",
            "Capital",
            "Credit Union",
            "Financial Advisors",
            "Financial Corporation",
            "Financial Services",
            "Fund",
            "Insurance Company",
            "Lending",
            "Mortgage",
            "Non-bank lenders",
            "Introductory services",
            "M&A advisors",
            "Brokers services",
            "Pay day lenders"
        ]
    },
    "Healthcare": {
        keywords: [
            "Acupuncture",
            "Audiologists",
            "Beauticians/ Beauty salons",
            "Chiropractors",
            "Clinics",
            "Dieticians",
            "Drug Distribution",
            "ePharmacy",
            "Facial",
            "General Practice",
            "Gyms",
            "Health Screening",
            "Healthcare Consultants",
            "Home Healthcare",
            "Hospices",
            "Massage",
            "Medical",
            "Medical Practitioners",
            "Medical Schools",
            "Medical Staffing",
            "Medical Testing Labs",
            "Nails",
            "Nursing",
            "Nursing homes",
            "Nutritional Consulting",
            "Ophthalmology",
            "Opticians",
            "Pharmacy",
            "Pharmacists",
            "Phlebotomists",
            "Podiatry",
            "Psychologists",
            "Rehab Units",
            "Remote Patient Monitoring",
            "Speech Therapy",
            "Sports Injury",
            "STI Clinics and Health Centres",
            "Tanning",
            "Telemedicine",
            "Vets",
            "Wellness",
            "Anaesthetist",
            "Cardiologist",
            "Cardiothorcic Surgeon",
            "Dermatologist",
            "Endocrinologist",
            "Gastroenterologist",
            "Gynaecologist",
            "Maxillofacial Surgeon",
            "Neaurologist",
            "Oncologist",
            "Ophthalmologist",
            "Orthopaedic Surgeon",
            "Otolaryngologist",
            "Plastic Surgeon",
            "Psychiatrist",
            "Radiologist",
            "Rheumatologist",
            "Urologist",
            "Vascular Surgeon"
        ],
        avoid: [
            "Clinics",
            "Dieticians",
            "Drug Distribution",
            "ePharmacy",
            "Facial",
            "General Practice",
            "Health Screening",
            "Pharmacy",
            "Pharmacists",
            "Phlebotomists",
            "Psychologists",
            "Rehab Units",
            "Speech Therapy",
            "Wellness"
        ]
    },
    "Life Sciences": {
        keywords: [
            "Animal Products",
            "Bio",
            "Biotics",
            "Blood bank",
            "Cannabis",
            "CBD",
            "Clinical Trials",
            "Drugs",
            "Hemp",
            "Laboratories",
            "Medical Devices (MD)",
            "Nutra",
            "Pain Relief",
            "Patients",
            "Research and Development (R&D)",
            "Research Trials",
            "Stem cell bank",
            "Supplements (food, dietary)",
            "Therapeutic devices",
            "Vitamins"
        ],
        avoid: [
            "Animal Products",
            "Bio",
            "Biotics",
            "Blood bank",
            "Cannabis",
            "CBD",
            "Clinical Trials",
            "Drugs",
            "Hemp",
            "Laboratories",
            "Medical Devices (MD)",
            "Nutra",
            "Pain Relief",
            "Patients",
            "Research and Development (R&D)",
            "Research Trials",
            "Stem cell bank",
            "Supplements (food, dietary)",
            "Therapeutic devices",
            "Vitamins"
        ]
    },
    "Management Liability": {
        keywords: [
            "Crime",
            "Directors & Officers (D&O)",
            "Fiduciary"
        ]
    },
    "Media": {
        keywords: [
            "Advertising Agency",
            "Artist",
            "Author",
            "Blogger / Vlogger",
            "Broadcaster",
            "Communication Consultants",
            "Digital Marketing",
            "Event organisers",
            "Film and TV Distributor",
            "Film and TV Production",
            "Magazine, Book, Newspaper Publishers",
            "Marketing",
            "Marketing and PR Companies",
            "Marketing Consultants",
            "Multimedia Companies",
            "Music Producers / Publishers / Composers / Songwriters",
            "New Media / digital agencies",
            "Photographers",
            "PR Consultants",
            "Press agencies",
            "Producers (TV, Film, Commercials)",
            "Public Relations",
            "Radio Stations",
            "Social Media Agencies"
        ]
    },
    "Professions": {
        keywords: [
            "Agricultural consultants",
            "Business consultants",
            "Captives",
            "Civil Engineers",
            "Commercial lines insurance",
            "Conservation managers",
            "Construction",
            "Conveyancers",
            "Data processors",
            "Directional drillers",
            "Drilling consultants",
            "Driving / Haulage",
            "Education",
            "Electrical Engineers",
            "Engineering and technical",
            "Environmental Engineers",
            "Environmnetal consultants",
            "Estate agents (residential and commercial)",
            "Expert witnesses",
            "Feasibility studies",
            "Financial services",
            "Fire consultants",
            "Food consultants",
            "Foreclosure agents",
            "Geologists",
            "Geotechnical engineers",
            "Health and safelty consultants",
            "Hospitality",
            "HR consultants",
            "HVAC engineers",
            "Hydraulic / fire engineers",
            "Interim Management",
            "Interior designers",
            "Investigators",
            "IT / Telecommunications",
            "Land brokers",
            "Land surveyors",
            "Landscape architects",
            "Management consultants",
            "Mechanical engineers",
            "Other professional services",
            "Personal lines",
            "Project managers",
            "Property developers",
            "Property leasing firms",
            "Property management companies",
            "Property management firms",
            "Property surveyors",
            "Quality assurance consultants",
            "Quarterly surveyors",
            "Recruitment",
            "Risk retention groups",
            "Staffing",
            "Structural architects / engineers / surveyors",
            "Town planning engineers",
            "Training companies"
        ]
    },
    "Tech": {
        keywords: [
            "App developers",
            "Application service providers",
            "Bespoke software developers",
            "Business networking websites",
            "Computer games developers",
            "Corporate blogs",
            "Digital Marketing agencies",
            "Domain name registration (resellers)",
            "Educational games",
            "Email providers",
            "Encryption software providers",
            "Genealogy websites",
            "Hardware value added resellers",
            "Instant messaging applications",
            "Internet radio websites",
            "IT consultancy",
            "IT security consultants",
            "IT support and training",
            "Mobile content providers",
            "Mobile phone content developers",
            "Networking engineers",
            "Online dating agencies",
            "Online gaming providers",
            "Online games developers and publishers",
            "Online listings sites",
            "Packaged software developers",
            "Photo sharing websites",
            "Social networking websites",
            "Software value added resellers",
            "System integrators",
            "User-generated content sites",
            "Video sharing websites",
            "Web designers",
            "Web hosting (Reselling)",
            "Web-based communities",
            "Web-casters",
            "Web service providers"
        ]
    },
    "FinTech": {
        keywords: [
            "Digital & mobile banking services",
            "Digital lending",
            "Investment platforms",
            "Money transfer / payment services"
        ]
    }
};

function searchProfession() {
    const searchInput = document.getElementById('searchInput').value.toLowerCase();
    const resultDiv = document.getElementById('result');
    const keywordsDiv = document.getElementById('keywords');
    const avoidDiv = document.getElementById('avoid');

    resultDiv.innerHTML = '';
    keywordsDiv.innerHTML = '';
    avoidDiv.innerHTML = '';

    const profession = professions.find(profession =>
        profession.name.toLowerCase() === searchInput
    );

    if (profession) {
        resultDiv.innerHTML = `The likely insurance type for a ${profession.name} is ${profession.insurance}.`;
        const insuranceType = profession.insurance;

        if (keywordsData[insuranceType]) {
            if (keywordsData[insuranceType].keywords) {
                keywordsDiv.innerHTML = `<h2>${insuranceType.toUpperCase()} Keywords</h2><ul>` + 
                    keywordsData[insuranceType].keywords.map(keyword => `<li>${keyword}</li>`).join('') + 
                    `</ul>`;
            }

            if (keywordsData[insuranceType].avoid) {
                avoidDiv.innerHTML = `<h2>Indicators to AVOID, consider selecting ${insuranceType.toUpperCase()}</h2><ul>` + 
                    keywordsData[insuranceType].avoid.map(keyword => `<li>${keyword}</li>`).join('') + 
                    `</ul>`;
            }
        }
    } else {
        resultDiv.innerHTML = 'Profession not found. Please check your input and try again.';
    }
}
